#本文件主要解释安全配置内容

#keywords:主要对ddl和dml关键字进行标记，
#value表示关键字值，level关键字等级(0表示最高级别依次级别降低)，status状态标识（0表示不需要标记，1表示需要标记）。

#rules:表示一些规则，主要涉及性能规则和正则表达式。condition表示规则条件，include（0表示包含，1表示不包含），
#subquery表示子查询数量，keyNumber表示条件的数量；regular表示正则表达式，function表示正则表达式功能。

#symbol:表示标记拦截符号。

#clazz:表示选用的决策类标识。

#主要的设计模式是策略模式，目前预定义策略为读取规则配置文件进行拦截，如果本策略无法满足需要您可以使用自己的安全策略来扩展。
#项目主要包含sql拦截和日志采集，所有的入口直接调用util方法，不用关心内部具体的实现逻辑。
